//! Replays `contracts/fixtures/board.json` — generated by running astrid-web's own
//! `lib/project-status.ts` — against this crate's port.
//!
//! The board is the surface where a disagreement is invisible rather than loud. A card in the wrong
//! column looks like somebody moved it; a card in no column looks like it was deleted. Neither
//! raises an error anywhere, on any client, so the answers here come from web rather than from a
//! reading of web.
//!
//! What is locked: the columns a configuration produces, which column every kind of card lands in,
//! what dragging each card onto each column writes, and what a new card in each column is created
//! with.

use astrid_core::board::{self, BoardColumn, ColumnKind};
use astrid_core::model::{Task, TaskList};
use serde::Deserialize;

const FIXTURE: &str = include_str!("../../../contracts/fixtures/board.json");

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Fixture {
    virtual_inbox_column_id: String,
    virtual_done_column_id: String,
    lists: Vec<FixtureList>,
    project_id: String,
    domain_task_ids: Vec<String>,
    configurations: Vec<Configuration>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct FixtureList {
    id: String,
    name: String,
    project_id: Option<String>,
    list_type: Option<String>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Configuration {
    name: String,
    custom_states: Option<serde_json::Value>,
    columns: Vec<FixtureColumn>,
    cards: Vec<Card>,
    creates: Vec<Create>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct FixtureColumn {
    id: String,
    name: String,
    description: String,
    kind: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Card {
    id: String,
    completed: bool,
    status_role: Option<String>,
    list_ids: Vec<String>,
    column_id: String,
    moves: Vec<Move>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Move {
    column_id: String,
    result: MoveResult,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct MoveResult {
    list_ids: Vec<String>,
    completed: bool,
    status_role: Option<String>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Create {
    column_id: String,
    with_domain_list: CreateResult,
    without_domain_list: CreateResult,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct CreateResult {
    #[serde(default)]
    list_ids: Option<Vec<String>>,
    #[serde(default)]
    status_role: Option<String>,
}

fn fixture() -> Fixture {
    serde_json::from_str(FIXTURE).expect("contracts/fixtures/board.json parses")
}

fn lists(fixture: &Fixture) -> Vec<TaskList> {
    fixture
        .lists
        .iter()
        .map(|list| TaskList {
            project_id: list.project_id.clone(),
            list_type: list.list_type.clone(),
            ..TaskList::new(&list.id, &list.name)
        })
        .collect()
}

fn task(card: &Card) -> Task {
    Task {
        completed: card.completed,
        status_role: card.status_role.clone(),
        list_ids: Some(card.list_ids.clone()),
        ..Task::new(&card.id, &card.id)
    }
}

fn kind_name(kind: ColumnKind) -> &'static str {
    match kind {
        ColumnKind::Inbox => "inbox",
        ColumnKind::Status => "status",
        ColumnKind::Done => "done",
    }
}

#[test]
fn the_virtual_column_ids_match_web() {
    let fixture = fixture();
    assert_eq!(
        board::VIRTUAL_INBOX_COLUMN_ID,
        fixture.virtual_inbox_column_id
    );
    assert_eq!(
        board::VIRTUAL_DONE_COLUMN_ID,
        fixture.virtual_done_column_id
    );
}

#[test]
fn every_configuration_produces_the_same_columns_web_produces() {
    for configuration in fixture().configurations {
        let built = board::columns(configuration.custom_states.as_ref());
        assert_eq!(
            built.len(),
            configuration.columns.len(),
            "{}: column count",
            configuration.name
        );
        for (ours, theirs) in built.iter().zip(configuration.columns.iter()) {
            assert_eq!(ours.id, theirs.id, "{}: column id", configuration.name);
            assert_eq!(
                ours.name, theirs.name,
                "{}: column name",
                configuration.name
            );
            assert_eq!(
                ours.description, theirs.description,
                "{}: column description",
                configuration.name
            );
            assert_eq!(
                kind_name(ours.kind),
                theirs.kind,
                "{}: column kind",
                configuration.name
            );
        }
    }
}

#[test]
fn every_card_lands_in_the_column_web_puts_it_in() {
    for configuration in fixture().configurations {
        let built = board::columns(configuration.custom_states.as_ref());
        for card in &configuration.cards {
            assert_eq!(
                board::column_for(&task(card), &built),
                card.column_id,
                "{}: {}",
                configuration.name,
                card.id
            );
        }
    }
}

#[test]
fn every_move_writes_what_web_writes() {
    let fixture = fixture();
    let lists = lists(&fixture);
    for configuration in &fixture.configurations {
        let built = board::columns(configuration.custom_states.as_ref());
        for card in &configuration.cards {
            for expected in &card.moves {
                let column = column(&built, &expected.column_id);
                let moved = board::resolve_move(&task(card), column, &lists);
                let label = format!(
                    "{}: {} → {}",
                    configuration.name, card.id, expected.column_id
                );
                assert_eq!(moved.list_ids, expected.result.list_ids, "{label}: lists");
                assert_eq!(
                    moved.completed, expected.result.completed,
                    "{label}: completed"
                );
                assert_eq!(
                    moved.status_role, expected.result.status_role,
                    "{label}: role"
                );
            }
        }
    }
}

#[test]
fn a_new_card_carries_what_web_would_send() {
    for configuration in fixture().configurations {
        let built = board::columns(configuration.custom_states.as_ref());
        for expected in &configuration.creates {
            let column = column(&built, &expected.column_id);
            let label = format!("{}: {}", configuration.name, expected.column_id);

            let with = board::resolve_create(column, Some("domain-1"));
            assert_eq!(
                with.list_ids, expected.with_domain_list.list_ids,
                "{label}: lists"
            );
            assert_eq!(
                with.status_role, expected.with_domain_list.status_role,
                "{label}: role"
            );

            let without = board::resolve_create(column, None);
            assert_eq!(
                without.list_ids, expected.without_domain_list.list_ids,
                "{label}: lists with no domain list"
            );
            assert_eq!(
                without.status_role, expected.without_domain_list.status_role,
                "{label}: role with no domain list"
            );
        }
    }
}

#[test]
fn the_same_cards_belong_on_the_board() {
    let fixture = fixture();
    let lists = lists(&fixture);
    let cards: Vec<Task> = fixture.configurations[0]
        .cards
        .iter()
        .map(task)
        .collect::<Vec<_>>();

    let found: Vec<&str> = board::domain_tasks(&cards, &lists, &fixture.project_id)
        .iter()
        .map(|task| task.id.as_str())
        .collect();
    assert_eq!(found, fixture.domain_task_ids);
}

fn column<'a>(columns: &'a [BoardColumn], id: &str) -> &'a BoardColumn {
    columns
        .iter()
        .find(|column| column.id == id)
        .unwrap_or_else(|| panic!("no column {id}"))
}
