//! The editing-session machine answers exactly as astrid-web's does.
//!
//! `contracts/fixtures/editing.json` is generated by running `lib/editing-session.ts` through
//! scripted sequences; each step here replays the same sequence and compares every field the
//! web reported — the active editor, what to commit, what to revert.

use astrid_core::editing::{self, Session};

const FIXTURE: &str = include_str!("../../../contracts/fixtures/editing.json");

#[derive(serde::Deserialize)]
struct Fixture {
    sequences: Vec<Sequence>,
}

#[derive(serde::Deserialize)]
struct Sequence {
    name: String,
    steps: Vec<Step>,
}

#[derive(serde::Deserialize)]
struct Step {
    operation: String,
    editor: Option<String>,
    active: Option<String>,
    commit: Option<String>,
    cancel: Option<String>,
}

#[test]
fn every_scripted_sequence_matches_web() {
    let fixture: Fixture = serde_json::from_str(FIXTURE).expect("the fixture parses");
    assert!(fixture.sequences.len() >= 10);

    for sequence in &fixture.sequences {
        let mut session = Session::IDLE;
        for (index, step) in sequence.steps.iter().enumerate() {
            let editor = step.editor.as_deref().unwrap_or("");
            let transition = match step.operation.as_str() {
                "begin" => editing::begin(&session, editor),
                "end" => editing::end(&session, editor),
                "cancel" => editing::cancel(&session, editor),
                "commitAll" => editing::commit_all(&session),
                other => panic!("unknown operation {other}"),
            };
            let at = format!(
                "{} — step {} ({} {editor})",
                sequence.name,
                index + 1,
                step.operation
            );
            assert_eq!(
                transition.session.active, step.active,
                "{at}: active editor"
            );
            assert_eq!(transition.commit, step.commit, "{at}: what to commit");
            assert_eq!(transition.cancel, step.cancel, "{at}: what to revert");
            session = transition.session;
        }
    }
}
