//! The search-query parser answers exactly as astrid-web's does.
//!
//! `contracts/fixtures/search.json` is generated by running `lib/search-query-parser.ts` over a
//! set of queries — every alias, the quoting rule, the identifier shape, the unknown-key
//! fallback. Each is parsed here and compared as JSON, field for field.

use astrid_core::parse::search;

const FIXTURE: &str = include_str!("../../../contracts/fixtures/search.json");

#[derive(serde::Deserialize)]
struct Fixture {
    priority_numbers: std::collections::BTreeMap<String, i64>,
    queries: Vec<Case>,
}

#[derive(serde::Deserialize)]
struct Case {
    query: String,
    parsed: serde_json::Value,
    is_empty: bool,
}

#[test]
fn every_query_parses_as_web_parses_it() {
    let fixture: Fixture = serde_json::from_str(
        &FIXTURE
            .replace("\"priorityNumbers\"", "\"priority_numbers\"")
            .replace("\"isEmpty\"", "\"is_empty\""),
    )
    .expect("the fixture parses");
    assert!(fixture.queries.len() >= 30);

    for case in &fixture.queries {
        let parsed = search::parse(&case.query);
        let ours = serde_json::to_value(&parsed).expect("serialises");
        assert_eq!(ours, case.parsed, "query {:?}", case.query);
        assert_eq!(
            parsed.is_empty(),
            case.is_empty,
            "query {:?}: is_empty",
            case.query
        );
    }

    for (word, number) in &fixture.priority_numbers {
        assert_eq!(search::priority_to_number(word), *number, "priority {word}");
    }
}
