//! Replays `contracts/fixtures/statuses.json` — generated by running astrid-web's own
//! `lib/project-custom-states.ts` — against this crate's port (task e5214fba).
//!
//! Writing a board's columns is arithmetic with sharp edges: which role a new column mints (and
//! the suffix when the slug is taken), which names are refused and with what message, that a
//! rename keeps the role so no task is orphaned, that only custom columns move or go, and the
//! exact array the server stores afterwards — including the order it stores it in. A port that
//! got any of those wrong would make a board that reads differently on the two clients, which
//! nothing raises an error about. So the answers come from web.

use astrid_core::board::{self, CustomState, ReorderDirection, StateErrorKind};
use serde::Deserialize;

const FIXTURE: &str = include_str!("../../../contracts/fixtures/statuses.json");

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Fixture {
    max_status_name_length: usize,
    boards: std::collections::HashMap<String, Option<serde_json::Value>>,
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    op: String,
    board: String,
    #[serde(default)]
    name: Option<String>,
    #[serde(default)]
    role: Option<String>,
    #[serde(default)]
    direction: Option<String>,
    result: Outcome,
}

#[derive(Deserialize)]
#[serde(untagged)]
enum Outcome {
    Refused { error: String, message: String },
    Written { states: Vec<State>, state: State },
}

#[derive(Deserialize, Debug, PartialEq, Eq)]
struct State {
    role: String,
    name: String,
    #[serde(default)]
    description: Option<String>,
    order: i64,
}

fn as_state(state: &CustomState) -> State {
    State {
        role: state.role.clone(),
        name: state.name.clone(),
        description: state.description.clone(),
        order: state.order,
    }
}

fn kind_name(kind: StateErrorKind) -> &'static str {
    match kind {
        StateErrorKind::Invalid => "invalid",
        StateErrorKind::Duplicate => "duplicate",
        StateErrorKind::Reserved => "reserved",
        StateErrorKind::NotFound => "not-found",
    }
}

#[test]
fn every_status_write_answers_as_web_does() {
    let fixture: Fixture = serde_json::from_str(FIXTURE).expect("a readable fixture");
    assert_eq!(
        fixture.max_status_name_length,
        board::MAX_STATUS_NAME_LENGTH
    );
    assert!(fixture.cases.len() >= 30, "the matrix shrank");

    for case in &fixture.cases {
        let raw = fixture
            .boards
            .get(&case.board)
            .unwrap_or_else(|| panic!("no board named {}", case.board))
            .as_ref();
        let label = format!(
            "{} on {} ({:?} {:?} {:?})",
            case.op, case.board, case.name, case.role, case.direction
        );
        let answer = match case.op.as_str() {
            "add" => board::add_custom_state(raw, case.name.as_deref().unwrap_or("")),
            "rename" => board::rename_state(
                raw,
                case.role.as_deref().unwrap_or(""),
                case.name.as_deref().unwrap_or(""),
            ),
            "reorder" => board::reorder_custom_state(
                raw,
                case.role.as_deref().unwrap_or(""),
                match case.direction.as_deref() {
                    Some("up") => ReorderDirection::Up,
                    _ => ReorderDirection::Down,
                },
            ),
            "remove" => board::remove_custom_state(raw, case.role.as_deref().unwrap_or("")),
            other => panic!("unknown op {other}"),
        };

        match (&case.result, answer) {
            (Outcome::Refused { error, message }, Err(refused)) => {
                assert_eq!(kind_name(refused.kind), error, "{label}: kind");
                assert_eq!(&refused.message, message, "{label}: message");
            }
            (Outcome::Written { states, state }, Ok(write)) => {
                assert_eq!(&as_state(&write.state), state, "{label}: the changed state");
                let ours: Vec<State> = write.states.iter().map(as_state).collect();
                assert_eq!(&ours, states, "{label}: the stored array");
            }
            (Outcome::Refused { error, .. }, Ok(write)) => {
                panic!(
                    "{label}: web refused ({error}) but this wrote {:?}",
                    write.state
                )
            }
            (Outcome::Written { state, .. }, Err(refused)) => {
                panic!(
                    "{label}: web wrote {state:?} but this refused: {}",
                    refused.message
                )
            }
        }
    }
}
