//! Who may do what to a list, and to the tasks in it.
//!
//! Canonical: `astrid-web/lib/list-permissions.ts`. Locked by
//! `contracts/fixtures/permissions.json`, which is generated by running that module.
//!
//! Two rules govern every function here, and both come from the shell rule in `docs/ASTRID.md` §0:
//!
//! - **The shell never compares a role string.** It asks a question — "may this person delete this
//!   list?" — and renders the answer. A `role == "admin"` written in XAML is the shape of bug where
//!   a control appears for someone who cannot use it, which is exactly what happened on Mac before
//!   `ListPermissions.swift` existed (task da56d096).
//! - **This answers what the client can see.** Web additionally derives a role from the list's
//!   project and from two legacy denormalised arrays. Those fields are not on the wire shape a
//!   client receives, so a client cannot reach those branches — see `docs/CONTRACTS.md` §5 for what
//!   that costs and who has to fix it.
//!
//! The server decides for real on every request. These functions decide what to *offer*, and being
//! wrong in either direction is a bug: too generous and the user gets a 403 from a button we drew,
//! too stingy and a collaborator silently loses their job with no error to explain it.

use serde::Deserialize;

/// Privacy value that opens a list to people with no membership.
///
/// Compared case-sensitively, matching web. Role strings are *not* — see [`normalized_role`] —
/// because roles are free text that has been written inconsistently, while privacy is a database
/// enum that has only ever been uppercase.
const PRIVACY_PUBLIC: &str = "PUBLIC";

/// Public lists whose viewers may add tasks. Any other value, including absent, behaves as
/// `copy_only`.
const PUBLIC_TYPE_COLLABORATIVE: &str = "collaborative";

#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ListRole {
    Owner,
    Admin,
    Member,
    Viewer,
}

#[derive(Debug, Clone, Deserialize)]
pub struct UserRef {
    pub id: String,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ListMembership {
    pub user_id: String,
    /// Optional because presence in the list IS membership; the role only refines what it allows.
    /// A row with a missing or unrecognised role must never revoke access.
    #[serde(default)]
    pub role: Option<String>,
    /// Some payloads carry the resolved user but a stale `user_id`.
    #[serde(default)]
    pub user: Option<UserRef>,
}

/// The part of a list that decides access.
///
/// A subset of the wire shape rather than the whole list: keeping it small means a caller cannot
/// accidentally make a permission decision depend on the list's colour, and it can be built from
/// any payload that carries these fields.
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ListAccess {
    pub owner_id: String,
    /// Checked as well as `owner_id`: some payloads carry the relation and a different id, and web
    /// treats either as ownership. A client comparing only `owner_id` locks the real owner out.
    #[serde(default)]
    pub owner: Option<UserRef>,
    pub privacy: String,
    #[serde(default)]
    pub public_list_type: Option<String>,
    #[serde(default)]
    pub list_members: Vec<ListMembership>,
}

impl ListAccess {
    fn is_public(&self) -> bool {
        self.privacy == PRIVACY_PUBLIC
    }

    fn is_public_collaborative(&self) -> bool {
        self.is_public() && self.public_list_type.as_deref() == Some(PUBLIC_TYPE_COLLABORATIVE)
    }

    /// A public list that is not collaborative — including one with no type set at all, which is
    /// the default and the overwhelmingly common case.
    fn is_public_copy_only(&self) -> bool {
        self.is_public() && !self.is_public_collaborative()
    }

    fn membership_of(&self, user_id: &str) -> Option<&ListMembership> {
        self.list_members
            .iter()
            .find(|m| m.user_id == user_id || m.user.as_ref().is_some_and(|u| u.id == user_id))
    }
}

/// Role strings are lowercased before they decide anything.
///
/// Casing must never decide access. Most writes are lowercase, but `app/api/v1/lists` created
/// members as `'MEMBER'`, so uppercase rows exist in the database already; matching exactly would
/// resolve those users to no access at all (astrid-web task e2803305). The Swift port still
/// compares exactly — see `docs/CONTRACTS.md` D6.
fn normalized_role(membership: &ListMembership) -> Option<String> {
    membership.role.as_ref().map(|r| r.to_lowercase())
}

/// The user's role on this list, or `None` for no access.
///
/// Precedence is the contract, not an implementation detail: ownership beats an admin membership,
/// an admin membership beats a plain one, and any membership beats the public viewer fallback. The
/// last of those is what stops a real collaborator on a public list being downgraded to read-only.
pub fn role_in_list(user_id: &str, list: &ListAccess) -> Option<ListRole> {
    if list.owner_id == user_id || list.owner.as_ref().is_some_and(|o| o.id == user_id) {
        return Some(ListRole::Owner);
    }

    if let Some(membership) = list.membership_of(user_id) {
        if normalized_role(membership).as_deref() == Some("admin") {
            return Some(ListRole::Admin);
        }
        // Presence is membership. Deliberately not a match on "member": an unrecognised or empty
        // role still means this person was added to this list.
        return Some(ListRole::Member);
    }

    if list.is_public() {
        return Some(ListRole::Viewer);
    }

    None
}

pub fn can_view_list(user_id: &str, list: &ListAccess) -> bool {
    role_in_list(user_id, list).is_some()
}

/// May this user add to and change tasks in this list at all?
///
/// The one place a viewer is granted a write: on a public *collaborative* list, anybody who can see
/// it can add to it. That is the entire point of the collaborative type.
pub fn can_edit_tasks(user_id: &str, list: &ListAccess) -> bool {
    let role = role_in_list(user_id, list);

    if list.is_public_collaborative() {
        return role.is_some();
    }

    has_role_at_least_member(role)
}

/// May this user change one specific task?
///
/// `task_creator_id` is `Option` because a task can arrive without one — an old row, or a payload
/// that did not include it. `None` can never equal the user, so an unattributed task on a public
/// collaborative list is not editable by a viewer. That is the safe direction: the server would
/// refuse anyway, and offering a control that 403s is worse than not offering it.
pub fn can_edit_task(user_id: &str, task_creator_id: Option<&str>, list: &ListAccess) -> bool {
    let role = role_in_list(user_id, list);

    if matches!(role, Some(ListRole::Owner) | Some(ListRole::Admin)) {
        return true;
    }

    if list.is_public_copy_only() {
        return role == Some(ListRole::Member);
    }

    if list.is_public_collaborative() {
        // Authorship, not role. A viewer may edit what they wrote; a member may not edit what they
        // did not. Public lists are the only place these two come apart.
        return task_creator_id == Some(user_id);
    }

    role == Some(ListRole::Member)
}

/// Does the user hold a real role, as opposed to being a passer-by on a public list?
///
/// Narrower than [`can_edit_tasks`], which also grants viewers on collaborative lists. The
/// difference matters wherever the client is deciding whether to apply an optimistic update: a
/// collaborative-list viewer must be excluded there, or the UI shows a change the server rejects.
pub fn has_explicit_list_role(user_id: &str, list: &ListAccess) -> bool {
    has_role_at_least_member(role_in_list(user_id, list))
}

/// Rename, image, defaults, filters, sharing.
pub fn can_manage_list(user_id: &str, list: &ListAccess) -> bool {
    matches!(
        role_in_list(user_id, list),
        Some(ListRole::Owner) | Some(ListRole::Admin)
    )
}

pub fn can_manage_members(user_id: &str, list: &ListAccess) -> bool {
    can_manage_list(user_id, list)
}

/// Deliberately its own question rather than an alias for [`can_manage_list`].
///
/// Deleting a shared list destroys other people's work, so it stays with the owner even though an
/// admin may change everything else about it.
pub fn can_delete_list(user_id: &str, list: &ListAccess) -> bool {
    role_in_list(user_id, list) == Some(ListRole::Owner)
}

fn has_role_at_least_member(role: Option<ListRole>) -> bool {
    matches!(
        role,
        Some(ListRole::Owner) | Some(ListRole::Admin) | Some(ListRole::Member)
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn list(privacy: &str, public_type: Option<&str>, members: Vec<ListMembership>) -> ListAccess {
        ListAccess {
            owner_id: "owner".into(),
            owner: None,
            privacy: privacy.into(),
            public_list_type: public_type.map(str::to_string),
            list_members: members,
        }
    }

    fn membership(user_id: &str, role: Option<&str>) -> ListMembership {
        ListMembership {
            user_id: user_id.into(),
            role: role.map(str::to_string),
            user: None,
        }
    }

    /// Covered by the fixture too, but stated here because it is the rule most likely to be
    /// "simplified" by someone who has not read astrid-web task e2803305.
    #[test]
    fn role_casing_never_decides_access() {
        for spelling in ["admin", "ADMIN", "Admin", "aDmIn"] {
            let l = list("PRIVATE", None, vec![membership("me", Some(spelling))]);
            assert_eq!(role_in_list("me", &l), Some(ListRole::Admin), "{spelling}");
        }
    }

    #[test]
    fn a_membership_row_grants_access_whatever_its_role_says() {
        for role in [Some("member"), Some("collaborator"), Some(""), None] {
            let l = list("PRIVATE", None, vec![membership("me", role)]);
            assert_eq!(role_in_list("me", &l), Some(ListRole::Member), "{role:?}");
        }
    }

    #[test]
    fn a_task_with_no_author_is_not_editable_by_a_viewer() {
        // The Option exists for real payloads, and the safe answer is no: the server would refuse,
        // and a control that 403s is worse than one that is absent.
        let l = list("PUBLIC", Some("collaborative"), vec![]);
        assert_eq!(role_in_list("me", &l), Some(ListRole::Viewer));
        assert!(!can_edit_task("me", None, &l));
    }

    #[test]
    fn an_unknown_public_type_is_treated_as_copy_only() {
        // Defaulting the other way would let a typo in one column open every task on a public list
        // to editing by strangers.
        let l = list("PUBLIC", Some("colaborative"), vec![]);
        assert!(!can_edit_tasks("me", &l));
    }

    #[test]
    fn privacy_is_matched_exactly_the_way_web_matches_it() {
        // Web compares `privacy === "PUBLIC"`. A lowercase value is not public, and pretending
        // otherwise here would make this client show a list the server treats as private.
        let l = list("public", None, vec![]);
        assert_eq!(role_in_list("me", &l), None);
    }
}
