//! The project board: which columns there are, which one a card is in, and what moving it writes.
//!
//! Ported from `astrid-web/lib/project-status.ts`, and locked by
//! `contracts/fixtures/board.json` — generated by running web's own implementation, because these
//! are branching rules whose precedence *is* the contract.
//!
//! ## A column id is a role
//!
//! Status began as membership in a `listType: "status"` list. That model could not hold two
//! requirements at once — one Ready/Doing/Waiting per person, and two members of a shared board
//! agreeing where a card is — and the same bug shipped twice before it moved onto the task as
//! `statusRole` and the rows were deleted.
//!
//! So: a column id is a role, Inbox and Done are derived from `completed` and the absence of a
//! role, and nothing is stored for either. **A role must never travel inside `listIds`** — the
//! server rejects the whole write when a list id does not exist ("Invalid list IDs: ready"), which
//! is how adding a card to a column silently broke across a deploy.
//!
//! ## An unknown role falls to Inbox
//!
//! A card whose role matches no rendered column is in *none* of them: gone from the board while
//! still present in the list. That is reachable whenever a board's custom columns have not loaded
//! yet. Showing a card in the wrong column is recoverable; losing it is not.

use serde::{Deserialize, Serialize};

use crate::model::{Task, TaskList};

/// The Inbox column's id. Virtual: no row exists for it.
pub const VIRTUAL_INBOX_COLUMN_ID: &str = "__virtual_inbox__";
/// The Done column's id. Virtual, like Inbox.
pub const VIRTUAL_DONE_COLUMN_ID: &str = "__virtual_done__";

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ColumnKind {
    Inbox,
    Status,
    Done,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BoardColumn {
    /// The role, for a status column; one of the two virtual ids otherwise.
    pub id: String,
    pub name: String,
    pub description: String,
    pub kind: ColumnKind,
}

/// One of the three roles every board shares.
///
/// Named rather than spelled as literals wherever they are used: a typo in `ready` is invisible,
/// because it returns an empty column, which reads exactly like a quiet day.
pub const READY_STATUS_ROLE: &str = "ready";
pub const DOING_STATUS_ROLE: &str = "doing";
pub const WAITING_STATUS_ROLE: &str = "waiting";

/// The defaults, as data rather than rows. Every board shows these three.
const DEFAULT_STATES: [(&str, &str, &str); 3] = [
    (READY_STATUS_ROLE, "Ready", "Time to get to work!"),
    (DOING_STATUS_ROLE, "Doing", "Active work in progress!"),
    (
        WAITING_STATUS_ROLE,
        "Waiting",
        "Paused until the circumstances are right.",
    ),
];

/// A board's own column, as stored in `Project.customStates`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CustomState {
    pub role: String,
    pub name: String,
    pub description: Option<String>,
    pub order: i64,
}

/// Read `customStates`, which is free-form JSON on the wire.
///
/// Anything unusable is dropped rather than guessed at: an entry with no role or no name cannot be
/// drawn or written back, and the first of a duplicated role wins. A board configured by a newer
/// web must still draw a usable board here.
pub fn parse_custom_states(raw: Option<&serde_json::Value>) -> Vec<CustomState> {
    let Some(serde_json::Value::Array(entries)) = raw else {
        return Vec::new();
    };
    let mut states: Vec<CustomState> = Vec::new();
    for entry in entries {
        let Some(object) = entry.as_object() else {
            continue;
        };
        let role = object
            .get("role")
            .and_then(|value| value.as_str())
            .unwrap_or_default()
            .trim()
            .to_string();
        let name = object
            .get("name")
            .and_then(|value| value.as_str())
            .unwrap_or_default()
            .trim()
            .to_string();
        if role.is_empty() || name.is_empty() {
            continue;
        }
        if states.iter().any(|held| held.role == role) {
            continue;
        }
        let order = object
            .get("order")
            .and_then(|value| value.as_i64())
            .unwrap_or(states.len() as i64);
        states.push(CustomState {
            role,
            name,
            description: object
                .get("description")
                .and_then(|value| value.as_str())
                .map(str::to_string),
            order,
        });
    }
    states.sort_by_key(|state| state.order);
    states
}

/// Whether a role is one of the three every board shares.
pub fn is_default_role(role: &str) -> bool {
    DEFAULT_STATES
        .iter()
        .any(|(default, _, _)| *default == role)
}

/// The board's columns, in order: Inbox, the three defaults, the board's own, then Done.
///
/// `custom_states` may also carry a *rename* of a default — an entry whose role is one of the
/// three. That renames the column rather than adding one, which is why the defaults are not simply
/// concatenated with the customs.
pub fn columns(custom_states: Option<&serde_json::Value>) -> Vec<BoardColumn> {
    let states = parse_custom_states(custom_states);
    let mut all = vec![BoardColumn {
        id: VIRTUAL_INBOX_COLUMN_ID.to_string(),
        name: "Inbox".into(),
        description: "Move them to \"Ready\" when they are... ready!".into(),
        kind: ColumnKind::Inbox,
    }];

    for (role, name, description) in DEFAULT_STATES {
        let renamed = states.iter().find(|state| state.role == role);
        all.push(BoardColumn {
            id: role.to_string(),
            name: renamed
                .map(|state| state.name.clone())
                .unwrap_or(name.into()),
            description: description.to_string(),
            kind: ColumnKind::Status,
        });
    }

    for state in states.iter().filter(|state| !is_default_role(&state.role)) {
        all.push(BoardColumn {
            id: state.role.clone(),
            name: state.name.clone(),
            description: state.description.clone().unwrap_or_default(),
            kind: ColumnKind::Status,
        });
    }

    all.push(BoardColumn {
        id: VIRTUAL_DONE_COLUMN_ID.to_string(),
        name: "Done".into(),
        description: "Complete — congrats!".into(),
        kind: ColumnKind::Done,
    });
    all
}

/// Which column a card is in.
///
/// Completed wins over any role it still carries: Done has no status. A role with no column falls
/// to Inbox — see the module note.
pub fn column_for(task: &Task, columns: &[BoardColumn]) -> String {
    if task.completed {
        return VIRTUAL_DONE_COLUMN_ID.to_string();
    }
    let Some(role) = task.status_role.as_deref().filter(|role| !role.is_empty()) else {
        return VIRTUAL_INBOX_COLUMN_ID.to_string();
    };
    columns
        .iter()
        .find(|column| column.kind == ColumnKind::Status && column.id == role)
        .map(|column| column.id.clone())
        .unwrap_or_else(|| VIRTUAL_INBOX_COLUMN_ID.to_string())
}

/// What dragging a card onto a column writes.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ColumnMove {
    /// The card's domain lists, unchanged — minus any leftover status membership.
    pub list_ids: Vec<String>,
    pub completed: bool,
    /// `None` for Inbox and Done, which have no status.
    pub status_role: Option<String>,
}

/// Resolve a move: Inbox clears the status, Done clears it and completes, a status column sets it.
///
/// Domain memberships are kept in every case. Any `listType: "status"` membership the client is
/// still holding is dropped: the rows are gone server-side, and leaving one attached would keep the
/// card rendering in its old column for anything that still reads membership.
pub fn resolve_move(task: &Task, target: &BoardColumn, lists: &[TaskList]) -> ColumnMove {
    let retained: Vec<String> = task
        .effective_list_ids()
        .into_iter()
        .filter(|id| {
            !lists
                .iter()
                .any(|list| &list.id == id && list.is_status_list())
        })
        .collect();

    match target.kind {
        ColumnKind::Inbox => ColumnMove {
            list_ids: retained,
            completed: false,
            status_role: None,
        },
        ColumnKind::Done => ColumnMove {
            list_ids: retained,
            completed: true,
            status_role: None,
        },
        // The role is never appended to the memberships: it is not a list id, and one bad id
        // rejects the whole write.
        ColumnKind::Status => ColumnMove {
            list_ids: retained,
            completed: false,
            status_role: Some(target.id.clone()),
        },
    }
}

/// What a new card in a column is created with.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ColumnCreate {
    /// `None` — not an empty list — when the board has no domain list to put it in: an empty array
    /// means "in no list", where absent lets the creator use its own default. Different writes.
    pub list_ids: Option<Vec<String>>,
    pub status_role: Option<String>,
}

pub fn resolve_create(target: &BoardColumn, domain_list_id: Option<&str>) -> ColumnCreate {
    ColumnCreate {
        list_ids: domain_list_id.map(|id| vec![id.to_string()]),
        status_role: match target.kind {
            ColumnKind::Status => Some(target.id.clone()),
            _ => None,
        },
    }
}

/// The cards that belong on a project's board.
///
/// Those in at least one of the project's domain lists. A task with only a status membership and no
/// domain list is not a project task.
pub fn domain_tasks<'a>(tasks: &'a [Task], lists: &[TaskList], project_id: &str) -> Vec<&'a Task> {
    let domain: Vec<&str> = lists
        .iter()
        .filter(|list| list.project_id.as_deref() == Some(project_id) && !list.is_status_list())
        .map(|list| list.id.as_str())
        .collect();
    tasks
        .iter()
        .filter(|task| {
            task.effective_list_ids()
                .iter()
                .any(|id| domain.contains(&id.as_str()))
        })
        .collect()
}

// ─── Writing a board's columns (task e5214fba) ────────────────────────────────────────────────
//
// Ported from `astrid-web/lib/project-custom-states.ts` and locked by
// `contracts/fixtures/statuses.json`, which records what web's own functions answer over a case
// matrix — including the array they store afterwards, in the order they store it.
//
// RENAME KEEPS THE ROLE. A task points at its column by `statusRole`; minting a fresh role on
// rename would orphan every task in that column. Removal has the same hazard, which is why the
// server clears the tasks a removed column held, and this client only asks it to.

/// Longest name that fits a column header without truncating — web's `MAX_STATUS_NAME_LENGTH`.
pub const MAX_STATUS_NAME_LENGTH: usize = 40;

/// Why a write was refused, as the web names it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum StateErrorKind {
    Invalid,
    Duplicate,
    Reserved,
    NotFound,
}

/// A refusal, with the web's own message so the two clients say the same thing.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct StateError {
    pub kind: StateErrorKind,
    pub message: String,
}

impl StateError {
    fn new(kind: StateErrorKind, message: impl Into<String>) -> Self {
        StateError {
            kind,
            message: message.into(),
        }
    }
}

/// A write that took: the full array to store, and the one state that changed.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StateWrite {
    pub states: Vec<CustomState>,
    pub state: CustomState,
}

/// Which way to move a column.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ReorderDirection {
    Up,
    Down,
}

impl CustomState {
    /// As the server stores it. A description is written only when there is one, as web's
    /// `StatusState` leaves the key off.
    pub fn to_json(&self) -> serde_json::Value {
        let mut value = serde_json::json!({
            "role": self.role,
            "name": self.name,
            "order": self.order,
        });
        if let Some(description) = &self.description {
            value["description"] = serde_json::Value::String(description.clone());
        }
        value
    }
}

/// The array the server stores, from the states a write produced.
pub fn states_to_json(states: &[CustomState]) -> serde_json::Value {
    serde_json::Value::Array(states.iter().map(CustomState::to_json).collect())
}

/// Web's `slugify`: lower-case, runs of anything but `a-z0-9` become one hyphen, hyphens are
/// trimmed from the ends, and nothing at all is "status".
fn slugify(name: &str) -> String {
    let mut slug = String::with_capacity(name.len());
    let mut pending_hyphen = false;
    for ch in name.to_lowercase().chars() {
        if ch.is_ascii_lowercase() || ch.is_ascii_digit() {
            if pending_hyphen && !slug.is_empty() {
                slug.push('-');
            }
            pending_hyphen = false;
            slug.push(ch);
        } else {
            pending_hyphen = true;
        }
    }
    if slug.is_empty() {
        "status".to_string()
    } else {
        slug
    }
}

/// Custom roles are namespaced `custom-…`, and suffixed `-2`, `-3`… when the slug is taken.
fn mint_role(name: &str, taken: &[String]) -> String {
    let base = format!("custom-{}", slugify(name));
    if !taken.iter().any(|role| role == &base) {
        return base;
    }
    let mut suffix = 2;
    loop {
        let candidate = format!("{base}-{suffix}");
        if !taken.iter().any(|role| role == &candidate) {
            return candidate;
        }
        suffix += 1;
    }
}

/// Web's `validateName`: the trimmed name, or why it will not do. `ignore_role` lets a state
/// keep its own name on rename.
fn validate_name(
    name: &str,
    states: &[CustomState],
    ignore_role: Option<&str>,
) -> Result<String, StateError> {
    let trimmed = name.trim();
    if trimmed.is_empty() {
        return Err(StateError::new(
            StateErrorKind::Invalid,
            "Status name cannot be empty",
        ));
    }
    if trimmed.encode_utf16().count() > MAX_STATUS_NAME_LENGTH {
        return Err(StateError::new(
            StateErrorKind::Invalid,
            format!("Status name is too long ({MAX_STATUS_NAME_LENGTH} characters max)"),
        ));
    }
    // Checked against the NAME rather than its slug: "Ready" slugs to `custom-ready`, which
    // collides with nothing, yet would put a second column called Ready on the board.
    if is_default_role(&trimmed.to_lowercase()) {
        return Err(StateError::new(
            StateErrorKind::Reserved,
            format!("\"{trimmed}\" is a built-in status"),
        ));
    }
    let lower = trimmed.to_lowercase();
    if states
        .iter()
        .any(|state| Some(state.role.as_str()) != ignore_role && state.name.to_lowercase() == lower)
    {
        return Err(StateError::new(
            StateErrorKind::Duplicate,
            "A status with that name already exists",
        ));
    }
    Ok(trimmed.to_string())
}

/// Add a column. The role is minted from the name; the order goes after every existing one.
pub fn add_custom_state(
    raw: Option<&serde_json::Value>,
    name: &str,
) -> Result<StateWrite, StateError> {
    let states = parse_custom_states(raw);
    let trimmed = validate_name(name, &states, None)?;
    let taken: Vec<String> = states.iter().map(|state| state.role.clone()).collect();
    let max_order = states.iter().map(|state| state.order).max().unwrap_or(-1);
    let state = CustomState {
        role: mint_role(&trimmed, &taken),
        name: trimmed,
        description: None,
        order: max_order + 1,
    };
    let mut all = states;
    all.push(state.clone());
    Ok(StateWrite { states: all, state })
}

/// Rename a column, whichever kind it is — the web's route dispatches the same way.
pub fn rename_state(
    raw: Option<&serde_json::Value>,
    role: &str,
    name: &str,
) -> Result<StateWrite, StateError> {
    if is_default_role(role) {
        rename_builtin_state(raw, role, name)
    } else {
        rename_custom_state(raw, role, name)
    }
}

/// A per-board name for one of the three built-ins: an override entry in `customStates`, the
/// role untouched so tasks keep routing by it.
fn rename_builtin_state(
    raw: Option<&serde_json::Value>,
    role: &str,
    name: &str,
) -> Result<StateWrite, StateError> {
    let Some((_, default_name, _)) = DEFAULT_STATES
        .iter()
        .find(|(default, _, _)| *default == role)
    else {
        return Err(StateError::new(
            StateErrorKind::Invalid,
            "Use renameCustomState for custom columns",
        ));
    };
    let default_order = DEFAULT_STATES
        .iter()
        .position(|(default, _, _)| *default == role)
        .unwrap_or(0) as i64;

    let trimmed = name.trim();
    if trimmed.is_empty() {
        return Err(StateError::new(
            StateErrorKind::Invalid,
            "Status name cannot be empty",
        ));
    }
    if trimmed.encode_utf16().count() > MAX_STATUS_NAME_LENGTH {
        return Err(StateError::new(
            StateErrorKind::Invalid,
            format!("Status name is too long ({MAX_STATUS_NAME_LENGTH} characters max)"),
        ));
    }
    // Not another built-in's name — but its own original name is fine ("Starting" → "Ready").
    let lower = trimmed.to_lowercase();
    if is_default_role(&lower) && lower != default_name.to_lowercase() {
        return Err(StateError::new(
            StateErrorKind::Reserved,
            format!("\"{trimmed}\" is a built-in status"),
        ));
    }
    let all = parse_custom_states(raw);
    if all
        .iter()
        .any(|state| state.role != role && state.name.to_lowercase() == lower)
    {
        return Err(StateError::new(
            StateErrorKind::Duplicate,
            "A status with that name already exists",
        ));
    }
    let existing = all.iter().find(|state| state.role == role);
    let state = CustomState {
        role: role.to_string(),
        name: trimmed.to_string(),
        description: None,
        order: existing.map(|state| state.order).unwrap_or(default_order),
    };
    // Any existing override for this role is replaced, and the new one goes last.
    let mut states: Vec<CustomState> = all.into_iter().filter(|state| state.role != role).collect();
    states.push(state.clone());
    Ok(StateWrite { states, state })
}

/// Rename a custom column in place. The role is deliberately preserved.
fn rename_custom_state(
    raw: Option<&serde_json::Value>,
    role: &str,
    name: &str,
) -> Result<StateWrite, StateError> {
    let states = parse_custom_states(raw);
    let Some(existing) = states.iter().find(|state| state.role == role) else {
        return Err(StateError::new(
            StateErrorKind::NotFound,
            "That status does not exist on this board",
        ));
    };
    let trimmed = validate_name(name, &states, Some(role))?;
    let state = CustomState {
        name: trimmed,
        ..existing.clone()
    };
    let states = states
        .into_iter()
        .map(|candidate| {
            if candidate.role == role {
                state.clone()
            } else {
                candidate
            }
        })
        .collect();
    Ok(StateWrite { states, state })
}

/// Move a custom column one slot. The three defaults have a fixed order and sit above every
/// custom column; at a boundary the move is a no-op that answers the unchanged board.
pub fn reorder_custom_state(
    raw: Option<&serde_json::Value>,
    role: &str,
    direction: ReorderDirection,
) -> Result<StateWrite, StateError> {
    if is_default_role(role) {
        return Err(StateError::new(
            StateErrorKind::Reserved,
            "Built-in status order cannot be changed",
        ));
    }
    let all = parse_custom_states(raw);
    let default_overrides: Vec<CustomState> = all
        .iter()
        .filter(|state| is_default_role(&state.role))
        .cloned()
        .collect();
    let mut sorted: Vec<CustomState> = all
        .iter()
        .filter(|state| !is_default_role(&state.role))
        .cloned()
        .collect();
    sorted.sort_by_key(|state| state.order);
    let Some(index) = sorted.iter().position(|state| state.role == role) else {
        return Err(StateError::new(
            StateErrorKind::NotFound,
            "That status does not exist on this board",
        ));
    };
    let swap = match direction {
        ReorderDirection::Up => index.checked_sub(1),
        ReorderDirection::Down => Some(index + 1).filter(|next| *next < sorted.len()),
    };
    let Some(swap) = swap else {
        let state = sorted[index].clone();
        let mut states = default_overrides;
        states.extend(sorted);
        return Ok(StateWrite { states, state });
    };
    // The two swap ORDER values and keep their positions in the array, which is what the
    // server stores and the fixture records.
    let (mine, theirs) = (sorted[index].order, sorted[swap].order);
    sorted[index].order = theirs;
    sorted[swap].order = mine;
    let state = sorted[index].clone();
    let mut states = default_overrides;
    states.extend(sorted);
    Ok(StateWrite { states, state })
}

/// Remove a custom column. The removed state is handed back because the tasks still carrying its
/// role have to be cleared — which the server does when asked.
pub fn remove_custom_state(
    raw: Option<&serde_json::Value>,
    role: &str,
) -> Result<StateWrite, StateError> {
    if is_default_role(role) {
        return Err(StateError::new(
            StateErrorKind::Reserved,
            "Built-in statuses cannot be removed",
        ));
    }
    let states = parse_custom_states(raw);
    let Some(existing) = states.iter().find(|state| state.role == role).cloned() else {
        return Err(StateError::new(
            StateErrorKind::NotFound,
            "That status does not exist on this board",
        ));
    };
    let states = states
        .into_iter()
        .filter(|state| state.role != role)
        .collect();
    Ok(StateWrite {
        states,
        state: existing,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn card(id: &str, completed: bool, role: Option<&str>, lists: &[&str]) -> Task {
        Task {
            completed,
            status_role: role.map(str::to_string),
            list_ids: Some(lists.iter().map(|id| id.to_string()).collect()),
            ..Task::new(id, id)
        }
    }

    fn ids(columns: &[BoardColumn]) -> Vec<&str> {
        columns.iter().map(|column| column.id.as_str()).collect()
    }

    #[test]
    fn a_board_is_inbox_the_three_defaults_and_done() {
        assert_eq!(
            ids(&columns(None)),
            vec![
                VIRTUAL_INBOX_COLUMN_ID,
                "ready",
                "doing",
                "waiting",
                VIRTUAL_DONE_COLUMN_ID
            ]
        );
    }

    /// A custom state whose role is a default renames that column rather than adding a second one.
    #[test]
    fn a_custom_state_can_rename_a_default_instead_of_adding_a_column() {
        let states = json!([
            { "role": "doing", "name": "In progress", "order": 1 },
            { "role": "review", "name": "In review", "order": 5 },
        ]);
        let built = columns(Some(&states));
        assert_eq!(
            ids(&built),
            vec![
                VIRTUAL_INBOX_COLUMN_ID,
                "ready",
                "doing",
                "waiting",
                "review",
                VIRTUAL_DONE_COLUMN_ID
            ]
        );
        assert_eq!(built[2].name, "In progress");
    }

    /// A board configured by a newer web must still draw. Unusable entries are dropped rather than
    /// guessed at, and the first of a duplicated role wins.
    #[test]
    fn unusable_custom_states_are_dropped() {
        let states = json!([
            { "role": "review", "name": "In review", "order": 0 },
            { "role": "review", "name": "Duplicate", "order": 1 },
            { "role": "", "name": "No role" },
            { "role": "nameless" },
            "not an object",
        ]);
        let built = columns(Some(&states));
        assert_eq!(
            ids(&built),
            vec![
                VIRTUAL_INBOX_COLUMN_ID,
                "ready",
                "doing",
                "waiting",
                "review",
                VIRTUAL_DONE_COLUMN_ID
            ]
        );
        assert_eq!(built[4].name, "In review");
    }

    #[test]
    fn a_card_is_in_the_column_its_role_names() {
        let built = columns(None);
        assert_eq!(
            column_for(&card("t1", false, Some("ready"), &[]), &built),
            "ready"
        );
        assert_eq!(
            column_for(&card("t2", false, None, &[]), &built),
            VIRTUAL_INBOX_COLUMN_ID
        );
    }

    /// Completed wins over a role the card still carries: Done has no status.
    #[test]
    fn a_finished_card_is_in_done_whatever_role_it_holds() {
        let built = columns(None);
        assert_eq!(
            column_for(&card("t1", true, Some("doing"), &[]), &built),
            VIRTUAL_DONE_COLUMN_ID
        );
    }

    /// Losing a card is worse than showing it in the wrong place.
    #[test]
    fn a_role_with_no_column_falls_to_inbox_rather_than_nowhere() {
        let built = columns(None);
        assert_eq!(
            column_for(&card("t1", false, Some("nowhere"), &[]), &built),
            VIRTUAL_INBOX_COLUMN_ID
        );
    }

    /// The role travels as a role. Putting it in `listIds` rejects the whole write.
    #[test]
    fn moving_to_a_status_column_sets_the_role_and_touches_no_membership() {
        let built = columns(None);
        let lists = vec![TaskList::new("domain-1", "Work")];
        let moved = resolve_move(&card("t1", false, None, &["domain-1"]), &built[1], &lists);
        assert_eq!(moved.status_role.as_deref(), Some("ready"));
        assert_eq!(moved.list_ids, vec!["domain-1"]);
        assert!(!moved.completed);
    }

    #[test]
    fn moving_to_done_completes_and_clears_the_role() {
        let built = columns(None);
        let moved = resolve_move(
            &card("t1", false, Some("ready"), &["domain-1"]),
            built.last().expect("done"),
            &[],
        );
        assert!(moved.completed);
        assert_eq!(moved.status_role, None);
    }

    #[test]
    fn moving_to_inbox_clears_the_role_without_completing() {
        let built = columns(None);
        let moved = resolve_move(&card("t1", false, Some("ready"), &[]), &built[0], &[]);
        assert!(!moved.completed);
        assert_eq!(moved.status_role, None);
    }

    /// A session open across the deploy still holds the deleted status rows. Leaving one attached
    /// would keep the card in its old column for anything that reads membership.
    #[test]
    fn a_move_strips_a_leftover_status_membership() {
        let built = columns(None);
        let stale: TaskList = serde_json::from_value(json!({
            "id": "stale", "name": "Ready", "listType": "status"
        }))
        .expect("decodes");
        let lists = vec![TaskList::new("domain-1", "Work"), stale];
        let moved = resolve_move(
            &card("t1", false, Some("ready"), &["domain-1", "stale"]),
            &built[2],
            &lists,
        );
        assert_eq!(moved.list_ids, vec!["domain-1"]);
    }

    /// Absent is not empty: an empty array means "in no list", where absent lets the creator use
    /// its own default.
    #[test]
    fn a_create_with_no_domain_list_leaves_the_memberships_out_entirely() {
        let built = columns(None);
        assert_eq!(resolve_create(&built[1], None).list_ids, None);
        assert_eq!(
            resolve_create(&built[1], Some("domain-1")).list_ids,
            Some(vec!["domain-1".to_string()])
        );
        assert_eq!(
            resolve_create(&built[0], Some("domain-1")).status_role,
            None
        );
    }

    /// A task with only a status membership is not a project task.
    #[test]
    fn only_cards_in_the_projects_own_lists_are_on_its_board() {
        let domain: TaskList = serde_json::from_value(json!({
            "id": "domain-1", "name": "Work", "projectId": "p1"
        }))
        .expect("decodes");
        let status: TaskList = serde_json::from_value(json!({
            "id": "stale", "name": "Ready", "projectId": "p1", "listType": "status"
        }))
        .expect("decodes");
        let elsewhere: TaskList = serde_json::from_value(json!({
            "id": "other", "name": "Other", "projectId": "p2"
        }))
        .expect("decodes");

        let tasks = vec![
            card("on-board", false, None, &["domain-1"]),
            card("orphan", false, None, &["stale"]),
            card("elsewhere", false, None, &["other"]),
        ];
        let found = domain_tasks(&tasks, &[domain, status, elsewhere], "p1");
        assert_eq!(
            found
                .iter()
                .map(|task| task.id.as_str())
                .collect::<Vec<_>>(),
            vec!["on-board"]
        );
    }
}
