//! One editing session at a time.
//!
//! Ported from `astrid-web/lib/editing-session.ts` (task 7b60c7c5; Apple 55010e29), and locked
//! by `contracts/fixtures/editing.json`, which is generated by running that file. The rule is a
//! product contract — `astrid-web/docs/PRODUCT_CONTRACT.md` §6 — because "what happens to my edit
//! when I click elsewhere" has to have the same answer on every client.
//!
//! The problem it removes: a dozen editors, each with its own `is_editing` flag and its own save
//! semantics, and nothing stopping two from being open at once. Every local fix for that ("close
//! the keyboard before opening the picker") was one instance of a rule nobody had written down.
//! So it is written down, once:
//!
//! - [`begin`]`(B)` **commits** and closes whatever was active, then activates B;
//! - [`end`]`(A)` commits A;
//! - [`cancel`]`(A)` reverts A — the only transition that reverts.
//!
//! **Commit on resign.** Tapping outside, opening another editor, navigating away and
//! backgrounding all save. Only an explicit Cancel reverts. One rule to learn, one rule to test.
//!
//! Because `begin` closes the previous editor by construction, mutual exclusion is a property of
//! this machine rather than something each call site has to remember.
//!
//! Pure: the caller performs the commit or cancel a transition names. The shell's view models hold
//! a [`Session`] and ask it before touching a field.

/// Which editor: `"title"`, `"description"`, `"lists"` — any name the caller chooses.
pub type EditorId = String;

/// The session: at most one editor open.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Session {
    pub active: Option<EditorId>,
}

impl Session {
    /// No editor open.
    pub const IDLE: Session = Session { active: None };

    /// True when `id` is the one open editor.
    pub fn is_active(&self, id: &str) -> bool {
        self.active.as_deref() == Some(id)
    }
}

/// What one transition asks the caller to do, and where the session is afterwards.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Transition {
    pub session: Session,
    /// The editor whose pending edit the caller must **commit**, if any.
    pub commit: Option<EditorId>,
    /// The editor whose pending edit the caller must **revert**, if any.
    pub cancel: Option<EditorId>,
}

fn transition(active: Option<&str>, commit: Option<&str>, cancel: Option<&str>) -> Transition {
    Transition {
        session: Session {
            active: active.map(str::to_string),
        },
        commit: commit.map(str::to_string),
        cancel: cancel.map(str::to_string),
    }
}

/// Open `id`, committing and closing whatever was active.
///
/// Re-opening the already-active editor is a no-op rather than a commit: a control re-rendering
/// must not silently save on its own behalf.
pub fn begin(session: &Session, id: &str) -> Transition {
    if session.is_active(id) {
        return transition(Some(id), None, None);
    }
    transition(Some(id), session.active.as_deref(), None)
}

/// Commit `id` and close the session.
///
/// A stale `end` — from an editor that `begin` already handed off — is ignored. Honouring it
/// would write the old editor's value over the new one's, and a blur routinely arrives after the
/// hand-off.
pub fn end(session: &Session, id: &str) -> Transition {
    if !session.is_active(id) {
        return transition(session.active.as_deref(), None, None);
    }
    transition(None, Some(id), None)
}

/// Revert `id` and close the session. Stale cancels are ignored, as with [`end`].
pub fn cancel(session: &Session, id: &str) -> Transition {
    if !session.is_active(id) {
        return transition(session.active.as_deref(), None, None);
    }
    transition(None, None, Some(id))
}

/// Close the session, committing whatever was open.
///
/// "Navigating away and backgrounding save": the policy applied to the events that are not a
/// specific editor's business.
pub fn commit_all(session: &Session) -> Transition {
    transition(None, session.active.as_deref(), None)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn opening_a_second_editor_commits_the_first() {
        let opened = begin(&Session::IDLE, "title");
        assert_eq!(opened.commit, None);
        assert!(opened.session.is_active("title"));

        let switched = begin(&opened.session, "description");
        assert_eq!(switched.commit.as_deref(), Some("title"));
        assert_eq!(switched.cancel, None);
        assert!(switched.session.is_active("description"));
    }

    /// A control re-rendering must not save on its own behalf.
    #[test]
    fn reopening_the_open_editor_is_a_no_op() {
        let opened = begin(&Session::IDLE, "title");
        let again = begin(&opened.session, "title");
        assert_eq!(again.commit, None);
        assert!(again.session.is_active("title"));
    }

    /// A blur that arrives after the hand-off must not write the old value over the new one.
    #[test]
    fn a_stale_end_is_ignored() {
        let opened = begin(&begin(&Session::IDLE, "title").session, "lists");
        let stale = end(&opened.session, "title");
        assert_eq!(stale.commit, None);
        assert!(stale.session.is_active("lists"), "the hand-off stands");
    }

    #[test]
    fn cancel_is_the_only_transition_that_reverts() {
        let opened = begin(&Session::IDLE, "title");
        let cancelled = cancel(&opened.session, "title");
        assert_eq!(cancelled.cancel.as_deref(), Some("title"));
        assert_eq!(cancelled.commit, None);
        assert_eq!(cancelled.session, Session::IDLE);
    }

    #[test]
    fn navigating_away_commits_whatever_was_open() {
        let opened = begin(&Session::IDLE, "description");
        let closed = commit_all(&opened.session);
        assert_eq!(closed.commit.as_deref(), Some("description"));
        assert_eq!(closed.session, Session::IDLE);
        assert_eq!(commit_all(&Session::IDLE).commit, None);
    }
}
