//! What a search box asks for.
//!
//! Ported from `astrid-web/lib/search-query-parser.ts` (task 5df85b9f) and locked by
//! `contracts/fixtures/search.json`, generated by running that file over the same queries. Turns
//! `assignee:me priority:high overdue rollover` into a structured filter plus the free text.
//!
//! The filter keys map onto the **existing** filter vocabulary — assignee, priority, due, state,
//! board status, list — rather than inventing a second one, so there is exactly one way to say
//! "high priority tasks assigned to me" in the product.
//!
//! Unknown keys degrade to free text rather than erroring: a search box must never punish a typo.
//! Somebody typing `hostname:foo` is searching for "hostname:foo", not making a mistake worth
//! shouting about.

use serde::Serialize;

/// A parsed query. Serialised in the web's field names so the fixture can be compared as JSON.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchQuery {
    /// Free-text terms, joined for the text match.
    pub text: String,
    /// `me`, or a handle or email with any leading `@` removed; absent when unfiltered.
    pub assignee: Option<String>,
    pub list_names: Vec<String>,
    pub label_names: Vec<String>,
    /// `none` | `low` | `medium` | `high`.
    pub priorities: Vec<String>,
    /// `today` | `overdue` | `week` | `month` | `none`.
    pub due: Option<String>,
    /// `open` | `done` | `canceled`.
    pub state: Option<String>,
    /// Board statuses; `none` means Inbox — no status at all.
    pub statuses: Vec<String>,
    /// A bare identifier (`AST-142`), upper-cased: a direct hit rather than a search term.
    pub identifier: Option<String>,
}

impl SearchQuery {
    /// Does this query ask for anything at all? An empty query returns nothing rather than every
    /// task the person can see: "no query" is not "show me everything".
    pub fn is_empty(&self) -> bool {
        self.text.is_empty()
            && self.assignee.is_none()
            && self.identifier.is_none()
            && self.due.is_none()
            && self.state.is_none()
            && self.list_names.is_empty()
            && self.label_names.is_empty()
            && self.priorities.is_empty()
            && self.statuses.is_empty()
    }
}

/// The number a priority word stands for, as stored on the task.
pub fn priority_to_number(priority: &str) -> i64 {
    match priority {
        "high" => 3,
        "medium" => 2,
        "low" => 1,
        _ => 0,
    }
}

fn priority_alias(value: &str) -> Option<&'static str> {
    Some(match value {
        "none" | "0" => "none",
        "low" | "1" => "low",
        "medium" | "med" | "2" => "medium",
        "high" | "3" | "urgent" => "high",
        _ => return None,
    })
}

fn due_alias(value: &str) -> Option<&'static str> {
    Some(match value {
        "today" => "today",
        "overdue" | "late" => "overdue",
        "week" | "this-week" => "week",
        "month" | "this-month" => "month",
        "none" | "never" => "none",
        _ => return None,
    })
}

fn state_alias(value: &str) -> Option<&'static str> {
    Some(match value {
        "open" | "incomplete" => "open",
        "done" | "complete" | "completed" => "done",
        "canceled" | "cancelled" => "canceled",
        _ => return None,
    })
}

/// `^[A-Za-z][A-Za-z0-9]{1,4}-\d+$`, spelled out.
fn is_identifier(token: &str) -> bool {
    let Some((key, number)) = token.split_once('-') else {
        return false;
    };
    let mut chars = key.chars();
    let first_is_letter = chars.next().is_some_and(|c| c.is_ascii_alphabetic());
    let rest_ok = chars.all(|c| c.is_ascii_alphanumeric());
    first_is_letter
        && rest_ok
        && (2..=5).contains(&key.len())
        && !number.is_empty()
        && number.chars().all(|c| c.is_ascii_digit())
}

/// Split on whitespace while respecting double quotes, so `list:"Bugs and Polish"` survives as
/// one token. The quotes themselves are dropped.
fn tokenize(query: &str) -> Vec<String> {
    let mut tokens = Vec::new();
    let mut current = String::new();
    let mut in_quotes = false;
    for c in query.chars() {
        if c == '"' {
            in_quotes = !in_quotes;
            continue;
        }
        if !in_quotes && c.is_whitespace() {
            if !current.is_empty() {
                tokens.push(std::mem::take(&mut current));
            }
            continue;
        }
        current.push(c);
    }
    if !current.is_empty() {
        tokens.push(current);
    }
    tokens
}

pub fn parse(query: &str) -> SearchQuery {
    let mut result = SearchQuery::default();
    let mut text = Vec::new();

    for token in tokenize(query) {
        if is_identifier(&token) {
            result.identifier = Some(token.to_uppercase());
            continue;
        }
        let Some(separator) = token.find(':') else {
            text.push(token);
            continue;
        };
        // `is:` with no value, or a leading colon — free text.
        if separator == 0 || separator == token.len() - 1 {
            text.push(token);
            continue;
        }
        let key = token[..separator].to_lowercase();
        let value = &token[separator + 1..];
        let normalized = value.to_lowercase();

        match key.as_str() {
            "assignee" | "owner" => {
                result.assignee = Some(if normalized == "me" {
                    "me".to_string()
                } else {
                    value.strip_prefix('@').unwrap_or(value).to_string()
                });
            }
            "list" => result.list_names.push(value.to_string()),
            "label" | "tag" => result.label_names.push(value.to_string()),
            "priority" | "p" => match priority_alias(&normalized) {
                Some(priority) => result.priorities.push(priority.to_string()),
                None => text.push(token),
            },
            "due" => match due_alias(&normalized) {
                Some(due) => result.due = Some(due.to_string()),
                None => text.push(token),
            },
            // Any non-empty value: a project's custom states are configurable, so the parser
            // cannot know the full set. An unmatched status finds nothing rather than erroring.
            "status" => result.statuses.push(normalized),
            "is" => match state_alias(&normalized) {
                Some(state) => result.state = Some(state.to_string()),
                None => text.push(token),
            },
            _ => text.push(token),
        }
    }

    result.text = text.join(" ").trim().to_string();
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn keys_become_filters_and_the_rest_is_text() {
        let parsed = parse("assignee:me priority:high overdue rollover");
        assert_eq!(parsed.assignee.as_deref(), Some("me"));
        assert_eq!(parsed.priorities, vec!["high".to_string()]);
        assert_eq!(parsed.text, "overdue rollover");
    }

    #[test]
    fn quotes_keep_a_list_name_together() {
        let parsed = parse("list:\"Bugs and Polish\" crash");
        assert_eq!(parsed.list_names, vec!["Bugs and Polish".to_string()]);
        assert_eq!(parsed.text, "crash");
    }

    /// A search box must never punish a typo.
    #[test]
    fn an_unknown_key_is_text_rather_than_an_error() {
        let parsed = parse("hostname:foo");
        assert_eq!(parsed.text, "hostname:foo");
        assert!(!parsed.is_empty());
    }

    #[test]
    fn a_bare_identifier_is_a_direct_hit() {
        let parsed = parse("ast-142");
        assert_eq!(parsed.identifier.as_deref(), Some("AST-142"));
        assert_eq!(parsed.text, "");
        assert!(!is_identifier("a-1"), "the key needs two characters");
        assert!(!is_identifier("toolong-1"));
        assert!(!is_identifier("1ab-2"));
    }

    #[test]
    fn nothing_asked_for_is_nothing() {
        assert!(parse("").is_empty());
        assert!(parse("   ").is_empty());
        assert!(parse("\"\"").is_empty());
    }
}
